apiVersion: v1
kind: ConfigMap
metadata:
  name: maoning-api-config
  namespace: maoning
data:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_USER: root
  MYSQL_DATABASE: maoning
  MINIO_ENDPOINT: http://minio:9000
  MINIO_BUCKET_MAOSHA: cat-litter
  MINIO_BUCKET_SHIYONG: maosha-shiyong
  MINIO_BUCKET_PUBLIC: public-assets
  WECHAT_APP_ID: wx4e2c5e940b617eee
