apiVersion: v1
kind: ConfigMap
metadata:
  name: maoning-api-config
  namespace: maoning
data:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_USER: root
  MYSQL_DATABASE: maoning
  MINIO_ENDPOINT: http://minio:9000
  MINIO_BUCKET_MAOSHA: cat-litter
  MINIO_BUCKET_SHIYONG: maosha-shiyong
  MINIO_BUCKET_PUBLIC: public-assets
  WECHAT_APP_ID: wx4e2c5e940b617eee
  DEEPSEEK_API_BASE: https://api.deepseek.com
  DEEPSEEK_MODEL: deepseek-v4-flash
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  CACHE_SHORT_TTL: "30"
  CACHE_DEFAULT_TTL: "60"
  CACHE_LONG_TTL: "120"
