apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maoning-api
  namespace: maoning
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: maoning-api
                port:
                  number: 5000
