apiVersion: v1
kind: Secret
metadata:
  name: maoning-secret
  namespace: maoning
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: maoning123
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: maoning-minio-123
  WECHAT_APP_SECRET: __SET_IN_CLUSTER_ONLY__
